### PR TITLE
remove remaining log references from runner

### PR DESCRIPTION
**Pull request by nruth**
This removes some remaining log references and a colouring call on string that doesn't exist for normal strings.

It got me to the state where the tests run, but I then hit other problems.

Still, this seems worth pulling since it's completing the previous pull request #2 , which has already been merged to master.

### CODE REVIEW

**Comment by jmuheim** [comment]
Oh I just noticed your PR right after I did the same changes myself. But thanks a lot for your help. Just try a `bundle update headhunter` (current version is `0.1.4`), then re-run your specs and tell me how far it's working for you.

**Comment by jmuheim** [comment]
By the way, the `.yellow` call shouldn't be a problem. Or is it for you? The line `s.add_dependency 'colorize'` in the `headhunter.gemspec` file should take care of this.

**Comment by nruth** [comment]
Right, that seems like a strange thing, but I did get errors from it so I deleted it without thinking about it much. 

I'll try again when I have chance, but I'm going away for a few weeks on unrelated stuff so it won't be soon. If you're going to set up automated tests it might be useful to look at how rspec-rails and/or cucumber-rails test their rails integration by using or generating a small rails app then running things against it and asserting about the terminal output (using the cucumber aruba extension, or similar).

I hope I can get this working at some point as I think the idea of getting all of this in one place is really convenient and solves several annoyances for my main project.

Thanks

**Comment by jmuheim** [comment]
Thanks for your hint with rspec-rails / cucumber-rails! This will definitely be useful.

I'm working on some first tests at the moment, let's see where this goes.

Have a good time and check back later, it's good to receive some feedback now and then. And I'm happy to hear that my idea doesn't appeal only to myself. :wink:

**Pull request closed without merging**
